package big.net;

import it.uniud.mads.jlibbig.core.attachedProperties.*;
import it.uniud.mads.jlibbig.core.std.*;

import java.util.*;
import java.util.concurrent.*;
/**
 * Class similar to "DFRule". It works with firewalls. If the router of the sender's domain has a firewall,
 * the packet must have a TokenIN to enter in the router's firewall. 
 * The TokenIN can be generated by the "NewTokenRule" class.
 * 
 * An important recommendation: in the redex and in the reactum, ALL the nodes should have a property. This
 * allows you to keep all the properties of the original bigraph even after the rule is performed.
 * 
 * @see DFRuleFW
 * @author Luca Geatti <geatti.luca@spes.uniud.it>
 *
 */
public class DFRuleFW extends RewritingRule{

	private Bigraph bigraph;
	private Bigraph redex;
	private Bigraph reactum;
	private Map<String, Node[]> rr;//Link from reactum node to redex nodes.
	private static LinkedList<String> auxProperties;	
	
	public DFRuleFW(Bigraph redex, Bigraph reactum, InstantiationMap map){
		super(redex, reactum, map);
		this.redex = redex;
		this.reactum = reactum;
		rr = new HashMap<String, Node[]>();
		createAssociations();
		this.auxProperties = new LinkedList<String>();
		auxProperties.add("NodeType");
		auxProperties.add("PacketType");
	}
	
	

	@Override
	public Iterable<Bigraph> apply(Bigraph b){
		this.bigraph = b;
		Iterable<Bigraph> bgl = super.apply(b);
		
		return bgl;
	}
	
	
	@Override
	public void instantiateReactumNode(Node original, Node instance, Match match){
		for(Property p : original.getProperties()){//Original = node of the reactum
			Node[] array = rr.get(p.get());
			if(array != null){
				Node n = array[1]; //Node of the redex
				if(n != null){
					Node img = match.getImage(n);//Node of the original bigraph
					if(img != null){
						copyProperties(img,instance);
					}
				}
			}
		}
		
	} 
	
	
	
	public static Bigraph getRedex(Signature signature){
		BigraphBuilder builder = new BigraphBuilder(signature);
		Root r1 = builder.addRoot();
		
		//Sender
		Node sender = builder.addNode("host", r1);
		sender.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","Sender")));
		builder.addSite(sender); //Site 0
		OuterName idS = builder.addOuterName("idS");
		OuterName localS = builder.addOuterName("localS");
		Node stackNode = builder.addNode("stackNode", sender, idS, localS);
		stackNode.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","stack_node")));
		//Firewall
		OuterName listFWIN = builder.addOuterName("listFWIN");
		OuterName listFWOUT = builder.addOuterName("listFWOUT");
		Node firewall = builder.addNode("firewall", r1, listFWIN, listFWOUT);
		firewall.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","Firewall")));
		//Router
		OuterName linkR = builder.addOuterName("linkR");
		Node router = builder.addNode("stackNode", firewall, linkR, localS);
		router.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","router")));
		//Packet
		OuterName idR = builder.addOuterName("idR");
		Node packet = builder.addNode("packet", sender, idS, idR);
		packet.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("PacketType","packet")));
		builder.addSite(packet); //Site 1
		//Token
		Node tokenIN = builder.addNode("tokenIN", packet, listFWIN, listFWOUT);
		tokenIN.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","token")));
		
		return builder.makeBigraph();
	}
	
	
	

	public static Bigraph getReactum(Signature signature){
		BigraphBuilder builder = new BigraphBuilder(signature);
		Root r1 = builder.addRoot();
		//Sender
		Node sender = builder.addNode("host", r1);
		sender.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","Sender")));
		builder.addSite(sender); //Site 0
		OuterName idS = builder.addOuterName("idS");
		OuterName localS = builder.addOuterName("localS");
		Node stackNode = builder.addNode("stackNode", sender, idS, localS);
		stackNode.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","stack_node")));
		//Firewall
		OuterName listFWIN = builder.addOuterName("listFWIN");
		OuterName listFWOUT = builder.addOuterName("listFWOUT");
		Node firewall = builder.addNode("firewall", r1, listFWIN,listFWOUT);
		firewall.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","Firewall")));
		//Router
		OuterName linkR = builder.addOuterName("linkR");
		Node router = builder.addNode("stackNode", firewall, linkR, localS);
		router.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("NodeType","router")));
		//Packet
		OuterName idR = builder.addOuterName("idR");
		Node packet = builder.addNode("packet", firewall, idS, idR);
		packet.attachProperty(new SharedProperty<String>(
				new SimpleProperty<String>("PacketType","packet")));
		builder.addSite(packet); //Site 1
		
		return builder.makeBigraph();
	}
	
	
	public static InstantiationMap getInstMap(){
		return new InstantiationMap(2, 0, 1);
	}
	
	

	
	private void copyProperties(Node from, Node to){
		for(Property p : from.getProperties()){
			if( !p.getName().equals("Owner") ){
				if( !p.getName().equals("NodeType") ){
					to.attachProperty(p);
				}
			}
		}
	}
	
	
	private void createAssociations(){
		
		for(Node n1 : this.reactum.getNodes()){
			for(Property p1 : n1.getProperties()){
				if( !p1.getName().equals("Owner") ){
					Node[] array = new Node[2];
					array[0] = n1;
					rr.put(p1.get().toString(), array);
				}
			}
		}
		
		for(Node n2 : this.redex.getNodes()){
			for(Property p2 : n2.getProperties()){
				if( !p2.getName().equals("Owner") ){
					Node[] array = rr.get(p2.get());
					if(array != null){
						array[1] = n2;
						rr.put(p2.get().toString(), array);
					}
				}
			}
		}
		
	}
	
	
	
	public static void clearAuxProperties(Bigraph bg){
		//Deletes auxiliary properties, such as NodeType and PacketType.
		boolean pass = false;
		for(Node n: bg.getNodes()){
				CopyOnWriteArrayList<Property> cow = new CopyOnWriteArrayList<Property>(n.getProperties());
				Property[] a = new Property[0];
				Property[] ap = cow.toArray( a );
				for(int i=0;i<ap.length;i++){
					String name = ap[i].getName();
					if( !name.equals("Owner") ){
						for(String str : auxProperties){
							if(name.equals(str)){
								pass = true;
							}
						}
						if(pass){
							n.detachProperty(ap[i]);
						}
						pass = false;
					}
				}
			}
	}
	
	
}
